version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - /home/ubuntu/db/data:/var/lib/postgresql/data 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      options:
        max-size: "10m"
        max-file: "5"
  app:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_URL: "redis://${REDIS_URL}:6379"
      ELASTICSEARCH_URL: "http://${ELASTICSEARCH_HOST}:9200"
    ports:
      - "3000:3000"
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    command: bundle exec rails s -b 0.0.0.0 -p 3000

  sidekiq:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_URL: "redis://${REDIS_URL}:6379" 
      ELASTICSEARCH_URL: "http://${ELASTICSEARCH_HOST}:9200"
    mem_limit: 512m
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    command: bundle exec sidekiq