version: '3'
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: import_sheets_development
    ports:
      - "5432:5432"

  web:
    image: your-username/noon-admin:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${PORT} -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:password@db:5432/import_sheets_development
      RAILS_ENV: development
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  bundle_cache: 