services:
  - type: web
    name: noon-admin
    env: ruby
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: bundle exec rails s -p $PORT -b 0.0.0.0
    envVars:
      - key: PORT
        value: 3000
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: noon-admin-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true

databases:
  - name: noon-admin-db
    databaseName: noon_admin_production
    ipAllowList: [] 